# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('value', models.FloatField()),
                ('weight', models.IntegerField()),
                ('charge', models.FloatField(default=0)),
                ('isAssigned', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deliveryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='distributionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('qualifications', models.TextField(blank=True, max_length=100)),
                ('profilePic', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numberPlate', models.CharField(max_length=10)),
                ('tonnage', models.IntegerField()),
                ('milleage', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('isAllocated', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dssWeb.driver')),
            ],
        ),
        migrations.AddField(
            model_name='consignment',
            name='deliveryStatus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dssWeb.deliveryState'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dssWeb.customer'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dssWeb.distributionPoint'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='truck',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dssWeb.truck'),
        ),
    ]
