# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssWeb', '0002_auto_20170416_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='arrivalTime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='departureTime',
            field=models.CharField(max_length=20),
        ),
    ]
