# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssWeb', '0004_auto_20170416_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedorders',
            name='customerName',
            field=models.CharField(max_length=100),
        ),
    ]
