# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssWeb', '0006_auto_20170416_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedorders',
            name='isAssigned',
            field=models.BooleanField(default=False),
        ),
    ]
