# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssWeb', '0007_importedorders_isassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedorders',
            name='custID',
            field=models.CharField(max_length=30),
        ),
    ]
