# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssWeb', '0008_auto_20170416_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custID',
            field=models.CharField(default='0000000', max_length=30),
        ),
        migrations.AddField(
            model_name='importedorders',
            name='charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='importedorders',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='importedorders',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='importedorders',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
